### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by longk15t** [longk15t/AutomationTest#1]
Build success!
Link of build: http://192.168.70.14:8080/job/StagePresence/38/
[Link build binary](\\192.168.70.17\Builds)

**Comment by phienpham** [comment]
file://///192.168.70.17/Builds

**Comment by phienpham** [comment]
file:///192.168.70.17/Builds

**Comment by phienpham** [comment]
file:///192.168.70.17/D:/Builds

**Comment by phienpham** [comment]
file:///192.168.70.17/D/Builds

**Comment by phienpham** [comment]
file:///192.168.70.17/F/Builds

**Comment by phienpham** [comment]
file:///192.168.70.17/F/workspace/Builds

**Comment by phienpham** [comment]
file://192.168.70.17/F/workspace/Builds

**Comment by phienpham** [comment]
file://192.168.70.17//Builds

**Comment by phienpham** [comment]
file://\\192.168.70.17/Builds

**Comment by phienpham** [comment]
file://\\192.168.70.17/Builds

**Comment by phienpham** [comment]
file://\\\192.168.70.17/Builds

**Comment by phienpham** [comment]
[asdasd](file://192.168.70.17/Builds)

**Comment by phienpham** [comment]
[asdasd](file:/192.168.70.17/Builds)

**Comment by phienpham** [comment]
[asdasd](http://192.168.70.17/Builds)

**Comment by phienpham** [comment]
[asdasd](file://///192.168.70.17/Builds)

**Comment by phienpham** [comment]
[file://///192.168.70.17/Builds]

**Comment by phienpham** [comment]
[file://192.168.70.17/Builds]

**Comment by phienpham** [comment]
\\192.168.70.17\Builds

**Comment by phienpham** [comment]
\\192.168.70.17\Builds

**Comment by phienpham** [comment]
\\\192.168.70.17\Builds
